insert into favourites ( user_id, map_id) values  3, 22);
insert into favourites ( user_id, map_id) values  11, 32);
insert into favourites ( user_id, map_id) values  31, 35);
insert into favourites ( user_id, map_id) values  30, 21);
insert into favourites ( user_id, map_id) values  2, 2);
insert into favourites ( user_id, map_id) values  37, 29);
insert into favourites ( user_id, map_id) values  15, 33);
insert into favourites ( user_id, map_id) values  9, 24);
insert into favourites ( user_id, map_id) values  13, 14);
insert into favourites ( user_id, map_id) values ( 26, 46);
insert into favourites ( user_id, map_id) values ( 7, 18);
insert into favourites ( user_id, map_id) values ( 25, 25);
insert into favourites ( user_id, map_id) values ( 1, 37);
insert into favourites ( user_id, map_id) values ( 40, 19);
insert into favourites ( user_id, map_id) values ( 43, 31);
insert into favourites ( user_id, map_id) values ( 36, 12);
insert into favourites ( user_id, map_id) values ( 34, 15);
insert into favourites ( user_id, map_id) values ( 49, 5);
insert into favourites ( user_id, map_id) values ( 42, 6);
insert into favourites ( user_id, map_id) values ( 28, 43);
insert into favourites ( user_id, map_id) values ( 12, 13);
insert into favourites ( user_id, map_id) values ( 50, 4);
insert into favourites ( user_id, map_id) values ( 44, 1);
insert into favourites ( user_id, map_id) values ( 48, 39);
insert into favourites ( user_id, map_id) values ( 5, 9);
insert into favourites ( user_id, map_id) values ( 16, 3);
insert into favourites ( user_id, map_id) values ( 22, 23);
insert into favourites ( user_id, map_id) values ( 29, 38);
insert into favourites ( user_id, map_id) values ( 18, 8);
insert into favourites ( user_id, map_id) values ( 41, 7);
insert into favourites ( user_id, map_id) values ( 14, 44);
insert into favourites ( user_id, map_id) values ( 27, 20);
insert into favourites ( user_id, map_id) values ( 21, 11);
insert into favourites ( user_id, map_id) values ( 32, 49);
insert into favourites ( user_id, map_id) values ( 4, 45);
insert into favourites ( user_id, map_id) values ( 46, 30);
insert into favourites ( user_id, map_id) values ( 19, 28);
insert into favourites ( user_id, map_id) values ( 20, 10);
insert into favourites ( user_id, map_id) values ( 39, 47);
insert into favourites ( user_id, map_id) values ( 23, 36);
insert into favourites ( user_id, map_id) values ( 17, 40);
insert into favourites ( user_id, map_id) values ( 47, 17);
insert into favourites ( user_id, map_id) values ( 8, 50);
insert into favourites ( user_id, map_id) values ( 38, 34);
insert into favourites ( user_id, map_id) values ( 33, 48);
insert into favourites ( user_id, map_id) values ( 10, 26);
insert into favourites ( user_id, map_id) values ( 6, 16);
insert into favourites ( user_id, map_id) values ( 24, 41);
insert into favourites ( user_id, map_id) values ( 35, 27);
insert into favourites ( user_id, map_id) values ( 45, 42);
